### ISSUE TITLE
`service.commands.XYZ` should map to a `lambda.Function` but it doesn't

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/eventual#391]
`service.commands.XYZ` should map to a `lambda.Function` but it doesn't

![image](https://github.com/functionless/eventual/assets/38672686/185ed422-05bb-4007-9996-9b61bb26aeb1)

**Comment by thantos** [comment]
The function is on `service.commands.XYZ.handler`. There is more to a command than just the lambda function. Right now the EventualResource which wraps the handler contains the logic for creating the principal when in local mode.

Other resources that use EventualResource: subscription, task, entity, bucket.

In the case of subscription, the exposed resource also contains the dead letter queue, it is not just a function.

A command may be the same in the future: handler, dynamic principal (local, etc), alarms, keys, etc.
